import { Inter } from "next/font/google";
import "./globals.css";
import StyledJsxRegistry from "@/lib/registry";
import Header from "@/components/common/header";
import Footer from "@/components/common/footer";
import { Box } from "@mui/material";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "StoryWeaver",
  description: "Generated by create next app",
};

import ClientLayout from "@/components/layouts/ClientLayout";

export default function RootLayout({ children }) {
  const isAdminRoute = children?.props?.childProp?.segment?.startsWith("admin");

  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledJsxRegistry>
          <ClientLayout isAdminRoute={isAdminRoute}>{children}</ClientLayout>
        </StyledJsxRegistry>
        <Toaster position="top-right" richColors expand={true} />
      </body>
    </html>
  );
}
