import { Inter } from "next/font/google";
import "./globals.css";
import StyledJsxRegistry from "@/lib/registry";
import Header from "@/components/common/header";
import Footer from "@/components/common/footer";
import { Box } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "StoryWeaver",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const isAdminRoute = children?.props?.childProp?.segment?.startsWith('admin');

  return (
    <html lang="en">
      <body className={inter.className}>
        {!isAdminRoute && <Header />}
        <Box sx={{ flex: 1 }}>
          <StyledJsxRegistry>{children}</StyledJsxRegistry>
        </Box>
        {!isAdminRoute && <Footer />}
      </body>
    </html>
  );
}
